server:
  port: 8080

springdoc:
  api-docs:
    path: /q/api-docs
  swagger-ui:
    path: /q/swagger-ui
  packages-to-scan: com.example.chatapp

springwolf:
  enabled: true
  docket:
    base-package: com.example.chatapp
    info:
      title: WebSocket Chat API
      version: 1.0.0
      description: AsyncAPI documentation for WebSocket-based chat application
    servers:
      stomp-server:
        protocol: stomp
        host: localhost:8080
  ui:
    defaults:
      show-bindings: true
      show-headers: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always